from config import TOTAL, UNMARRIED, MEDICAL_STATE, HOSPITALIZED, SICK, SIGNS_OBSERVED, ICD_9_DIAGNOSIS, UNKNOWN, VACCINATED_FOR_FLU, VACCINATED_FOR_PNEUMOCOCCUS


def create_data_row(case_type, mapped_data):
    return [
        case_type,
        mapped_data[case_type][TOTAL],
        mapped_data[case_type]["GJINIA"]['MESHKUJ'],
        mapped_data[case_type]["GJINIA"]['FEMRA'],
        mapped_data[case_type]['MOSHA']['0-1']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['0-1']['FEMRA'],
        mapped_data[case_type]['MOSHA']['1-18']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['1-18']['FEMRA'],
        mapped_data[case_type]['MOSHA']['19-25']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['19-25']['FEMRA'],
        mapped_data[case_type]['MOSHA']['26-34']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['26-34']['FEMRA'],
        mapped_data[case_type]['MOSHA']['35-70']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['35-70']['FEMRA'],
        mapped_data[case_type]['MOSHA']['>70']['MESHKUJ'],
        mapped_data[case_type]['MOSHA']['>70']['FEMRA'],
        mapped_data[case_type]['STATUSI']['MARTUAR'],
        mapped_data[case_type]['STATUSI'][UNMARRIED],
        mapped_data[case_type][MEDICAL_STATE]['SHERUAR'],
        mapped_data[case_type][MEDICAL_STATE][SICK],
        mapped_data[case_type][MEDICAL_STATE]['VDEKUR'],
        mapped_data[case_type][MEDICAL_STATE]['PANJOHUR'],
        mapped_data[case_type][HOSPITALIZED]['PO'],
        mapped_data[case_type][HOSPITALIZED]['JO'],
        mapped_data[case_type][HOSPITALIZED][UNKNOWN],
        mapped_data[case_type]['SIMPTOMA']['PO'],
        mapped_data[case_type]['SIMPTOMA']['JO'],
        mapped_data[case_type]['SIMPTOMA'][UNKNOWN],
        mapped_data[case_type][SIGNS_OBSERVED]['PO'],
        mapped_data[case_type][SIGNS_OBSERVED]['JO'],
        mapped_data[case_type][SIGNS_OBSERVED][UNKNOWN],
        mapped_data[case_type][ICD_9_DIAGNOSIS]['PO'],
        mapped_data[case_type][ICD_9_DIAGNOSIS]['JO'],
        mapped_data[case_type][VACCINATED_FOR_FLU]['PO'],
        mapped_data[case_type][VACCINATED_FOR_FLU]['JO'],
        mapped_data[case_type][VACCINATED_FOR_FLU][UNKNOWN],
        mapped_data[case_type][VACCINATED_FOR_PNEUMOCOCCUS]['PO'],
        mapped_data[case_type][VACCINATED_FOR_PNEUMOCOCCUS]['JO'],
        mapped_data[case_type][VACCINATED_FOR_PNEUMOCOCCUS][UNKNOWN],
    ]